/* ======================================================================
*   Copyright (C) 2023 Texas Instruments Incorporated
*
*   All rights reserved. Property of Texas Instruments Incorporated.
*   Restricted rights to use, duplicate or disclose this code are
*   granted through contract.
*
*   The program may not be used without the written permission
*   of Texas Instruments Incorporated or against the terms and conditions
*   stipulated in the agreement under which this program has been
*   supplied.
* ==================================================================== */
 /***************************************************************************
  Project: [!"$project"!]
  
  This file is generated by EB Tresos
  Do not modify this file, otherwise the software may behave in unexpected way.

 *****************************************************************************/

/**
 *  \file     Can_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file for
 *            CAN MCAL driver
 *
 */



#ifndef CAN_CFG_H_
#define CAN_CFG_H_

/**
 * \addtogroup CAN Can
 * @{
 */

[!IF "not(node:empty(as:modconf('Can')[1]/CanDemEventParameterRefs/*))"!][!//
#include "Dem.h"
[!ENDIF!][!//
[!IF "not(node:empty(as:modconf('Can')[1]/CanGeneral/CanOsCounterRef))"!][!//
#include "Os.h"
[!ENDIF!][!//
#ifdef __cplusplus
extern "C" {
#endif

 #ifndef DOXYGEN_SHOULD_SKIP_THIS

/** \brief CAN Config ID */
#define CAN_CFG_ID          (CAN_CFG_ID_0)

/**
*  \brief CAN Build Variant.
*   Build variants.(i.e Pre Compile,Post Build)
*/
[!IF "as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile'"!]
#define CAN_VARIANT_PRE_COMPILE (STD_ON)[!//
[!ELSE!]
#define CAN_VARIANT_POST_BUILD	(STD_ON)[!//
[!ENDIF!]

/**
 *  \name Can Driver Configuration SW Version Info
 *
 *  Defines for CAN Driver configuration version
 *  @{
 */
/** \brief Can configuration Major Version */
#define CAN_CFG_MAJOR_VERSION           ([!"substring-before($moduleSoftwareVer,'.')"!]U)
/** \brief Can configuration Minor Version */
#define CAN_CFG_MINOR_VERSION           ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)
/** \brief Can configuration Patch Version */
#define CAN_CFG_PATCH_VERSION           ([!"substring-after(substring-after($moduleSoftwareVer,'.'),'.')"!]U)
/* @} */


/**
 *  \name Can Driver Configuration SW Version Info
 *
 *  Pre-compile switches for enabling/disabling CAN MCAL APIs
 *  @{
 */
#define CAN_VERSION_INFO_API   [!IF "as:modconf('Can')[1]/CanGeneral/CanVersionInfoApi = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*!< Enable/Disable Can_GetVersionInfo() */

#define CAN_DEV_ERROR_DETECT  [!IF "as:modconf('Can')[1]/CanGeneral/CanDevErrorDetect = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*!< Enable/Disable DEV error detection */
#define CAN_DEINIT_API  [!IF "as:modconf('Can')[1]/CanGeneral/CanDeInitApi = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*!< Enable/Disable Can_DeInit() API */
#define CAN_SET_BAUDRATE_API  [!IF "as:modconf('Can')[1]/CanGeneral/CanSetBaudrateApi = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*!< Enable/Disable Can_SetBaudrate() API */
#define CAN_LOOPBACK_ENABLE   [!IF "as:modconf('Can')[1]/CanGeneral/CanLoopBackTest_Enable = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*!< Enable/Disable Can_TestLoopBackModeEnable() */
#define CAN_WAKEUP_FUNCTIONALITY_API        [!IF "count(as:modconf('Can')[1]/CanConfigSet/CanController/*[CanWakeupFunctionalityAPI = 'true']) > 0"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*!< Enable/Disable Can_CheckWakeup() */
#define CAN_MULTIPLEXED_TRANSMISSION_ENABLE [!IF "as:modconf('Can')[1]/CanGeneral/CanMultiplexedTransmission = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*!< Enable/Disable Multiplexed Transmission */
#define CAN_TRIGGER_TRANSMIT_ENABLE [!IF "count(as:modconf('Can')[1]/CanConfigSet/CanHardwareObject/*[CanTriggerTransmitEnable/* = 'true']) > 0"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*!< Enable/Disable CanIf_TriggerTransmit */

/**
*  \brief CAN Build Variant.
*   Build Variants.(i.e Pre-compile,Post-Build or Link time)
*/
[!IF "as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile'"!]
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
#define CAN_INIT_CONFIG_PC       [!"@name"!]
[!ENDLOOP!]
[!ENDIF!]
 /*mixed mode is allowed */
[!VAR "Txpolling" = "'0'"!][!//
[!VAR "Rxpolling" = "'0'"!][!//
[!VAR "BusOffpolling" = "'0'"!][!//
[!VAR "WakeUppolling" = "'0'"!][!//
[!LOOP "as:modconf('Can')[1]/CanConfigSet/CanController/*"!][!//
[!IF "CanRxProcessing = 'POLLING' or CanRxProcessing = 'MIXED' "!][!//
[!VAR "Rxpolling" = "$Rxpolling+1"!][!//
[!ENDIF!][!//
[!IF "CanTxProcessing = 'POLLING' or CanTxProcessing = 'MIXED' "!][!//
[!VAR "Txpolling" = "$Txpolling+1"!][!//
[!ENDIF!][!//
[!IF "CanBusoffProcessing = 'POLLING' "!][!//
[!VAR "BusOffpolling" = "$BusOffpolling+1"!][!//
[!ENDIF!][!//
[!IF "CanWakeupProcessing = 'POLLING' "!][!//
[!VAR "WakeUppolling" = "$WakeUppolling+1"!][!//
[!ENDIF!][!//
[!ENDLOOP!][!//

#define CAN_TX_POLLING      ([!IF "$Txpolling != num:i(0)"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])
/*!< Enable/Disable Can_MainFunction_Write */
#define CAN_RX_POLLING      ([!IF "$Rxpolling != num:i(0)"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])
/*!< Enable/Disable Can_MainFunction_Read */
#define CAN_BUSOFF_POLLING  ([!IF "$BusOffpolling != num:i(0)"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])
/*!< Enable/Disable Can_MainFunction_BusOff */
#define CAN_WAKEUP_POLLING  ([!IF "$WakeUppolling != num:i(0)"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])
/*!< Enable/Disable Can_MainFunction_Wakeup */
#define CAN_ECC_ENABLE      STD_OFF
/*!< Enable/Disable single bit ECC logic */
/* @} */

/*!< Maximum number of Config sets */
/*!< Max Baud rate config structs */
[!VAR "varmax" = "0"!][!//
[!LOOP "as:modconf('Can')[1]/CanConfigSet/CanController/*"!][!//
[!VAR "varmax" = "$varmax+1"!][!//
[!ENDLOOP!][!//
#define CAN_NUM_CONTROLLER          ([!"num:i($varmax)"!]U)
/*!< Max number of controllers defined*/

[!VAR "varmax" = "0"!][!//
[!LOOP "as:modconf('Can')[1]/CanConfigSet/CanHardwareObject/*"!][!//
[!VAR "varmax" = "$varmax+1"!][!//
[!ENDLOOP!][!//
#define CAN_NUM_MAILBOXES           ([!"num:i($varmax)"!]U)
/*!< Max number of mailboxes defined*/
[!//
#define CAN_MAX_CONTROLLER          (8U)
/*!< Max number of mailboxes per controller */[!//

[!VAR "txmailbox" = "0"!][!//
[!LOOP "as:modconf('Can')[1]/CanConfigSet/CanHardwareObject/*"!][!//
[!IF "CanObjectType = 'TRANSMIT'"!][!//
[!VAR "txmailbox"="$txmailbox+1"!][!//
[!ENDIF!][!//
[!ENDLOOP!][!//

#define CAN_NUM_TX_MAILBOXES 		([!"num:i($txmailbox)"!]U)
/*!< Total Number of TX mailboxes */

#define CAN_ISR_TYPE                ([!"as:modconf('Can')[1]/CanGeneral/CanTypeofInterruptFunction"!])
/*!< Enable/Disable OSEK Category 1 ISR */

/**
 *  \name Can Controller Id names
 *
 *  Defines for symbolic names for the CanControllerIds
 *  @{
 */
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!][!//
[!LOOP "CanController/*"!][!//
#define CanConf_CanController_[!"@name"!]   ([!"CanControllerId"!]U)
[!ENDLOOP!][!ENDLOOP!][!//
/* @} */

/* @} */

[!LOOP "as:modconf('Can')[1]/CanConfigSet/CanController/*"!][!//
#define CAN_CONTROLLER_[!"CanControllerInstance"!]
[!ENDLOOP!][!//
[!VAR "CanController0AlreadyConfigured" = "0"!][!//
[!VAR "CanController1AlreadyConfigured" = "0"!][!//
[!VAR "CanController2AlreadyConfigured" = "0"!][!//
[!VAR "CanController3AlreadyConfigured" = "0"!][!//
[!VAR "CanController4AlreadyConfigured" = "0"!][!//
[!VAR "CanController5AlreadyConfigured" = "0"!][!//
[!VAR "CanController6AlreadyConfigured" = "0"!][!//
[!VAR "CanController7AlreadyConfigured" = "0"!][!//
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!][!//
[!LOOP "CanController/*"!][!//
[!IF "CanControllerInstance = 'MCAN0'"!][!//
[!VAR "CanController0AlreadyConfigured" = "$CanController0AlreadyConfigured+1"!][!//
[!IF "(num:i($CanController0AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN0 is already configured"!][!ENDIF!][!//
[!ENDIF!][!//
[!IF "CanControllerInstance = 'MCAN1'"!][!//
[!VAR "CanController1AlreadyConfigured" = "$CanController1AlreadyConfigured+1"!][!//
[!IF "(num:i($CanController1AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN1 is already configured"!][!ENDIF!][!//
[!ENDIF!][!//
[!IF "CanControllerInstance = 'MCAN2'"!][!//
[!VAR "CanController2AlreadyConfigured" = "$CanController2AlreadyConfigured+1"!][!//
[!IF "(num:i($CanController2AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN2 is already configured"!][!ENDIF!][!//
[!ENDIF!][!//
[!IF "CanControllerInstance = 'MCAN3'"!][!//
[!VAR "CanController3AlreadyConfigured" = "$CanController3AlreadyConfigured+1"!][!//
[!IF "(num:i($CanController3AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN3 is already configured"!][!ENDIF!][!//
[!ENDIF!][!//
[!IF "CanControllerInstance = 'MCAN4'"!][!//
[!VAR "CanController4AlreadyConfigured" = "$CanController4AlreadyConfigured+1"!][!//
[!IF "(num:i($CanController4AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN4 is already configured"!][!ENDIF!][!//
[!ENDIF!][!//
[!IF "CanControllerInstance = 'MCAN5'"!][!//
[!VAR "CanController5AlreadyConfigured" = "$CanController5AlreadyConfigured+1"!][!//
[!IF "(num:i($CanController5AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN5 is already configured"!][!ENDIF!][!//
[!ENDIF!][!//
[!IF "CanControllerInstance = 'MCAN6'"!][!//
[!VAR "CanController6AlreadyConfigured" = "$CanController6AlreadyConfigured+1"!][!//
[!IF "(num:i($CanController6AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN6 is already configured"!][!ENDIF!][!//
[!ENDIF!][!//
[!IF "CanControllerInstance = 'MCAN7'"!][!//
[!VAR "CanController7AlreadyConfigured" = "$CanController7AlreadyConfigured+1"!][!//
[!IF "(num:i($CanController7AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN7 is already configured"!][!ENDIF!][!//
[!ENDIF!][!//
[!ENDLOOP!][!ENDLOOP!][!//

/**
 *  \name Can HW Object names
 *
 *  Defines for symbolic names for the CanHardwareObjectIds
 *  @{
 */
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!][!//
[!VAR "CanObjectIdIndx" = "0"!]
[!LOOP "CanHardwareObject/*"!][!//
#define CanConf_CanHardwareObject_[!"@name"!]   ([!"CanObjectId"!]U)
#define CAN_HTRH_[!"@index"!]         (CanConf_CanHardwareObject_[!"@name"!])
[!IF "(num:i($CanObjectIdIndx)) != CanObjectId"!][!ERROR "Can Object Id should start with 0,should be unique, increment by 1 and continue without any gaps"!][!ENDIF!][!//
[!VAR "CanObjectIdIndx" = "$CanObjectIdIndx+1"!]
[!ENDLOOP!][!ENDLOOP!][!//
/* @} */

/* @} */

/** \brief Counter ID for counter used to count wait ticks */
#define CAN_OS_COUNTER_ID               ((CounterType)[!IF "not(node:empty(as:modconf('Can')[1]/CanGeneral/CanOsCounterRef))"!][!"node:name(node:ref(as:modconf('Can')[1]/CanGeneral/CanOsCounterRef))"!][!ELSE!][!"as:modconf('Can')[1]/CanGeneral/CanDefaultOSCounterId"!]U[!ENDIF!])

/**
*  \brief CAN timeout - used in CAN IFCMD busy wait and Start/Stop busy wait.
*   Specifies the maximum time for blocking function until a timeout is detected.
*   Unit is milli seconds.
*/
#define CAN_TIMEOUT_DURATION            ([!"num:i(num:mul(as:modconf('Can')[1]/CanGeneral/CanTimeoutDuration,1000))"!]U)

[!IF "node:exists(as:modconf('Can')[1]/CanGeneral/CanLPduReceiveCalloutFunction/*) = 'true'"!]
/**
*  \brief CAN LPdu Callout - This parameter defines the existence and the name 
*	of a callout function that is called after a successful reception of a 
*	received CAN Rx L-PDU. If this parameter is omitted no callout shall 
*	take place.
*/
#define CAN_LPDU_CALLOUT            [!"as:modconf('Can')[1]/CanGeneral/CanLPduReceiveCalloutFunction/*"!]
extern boolean [!"as:modconf('Can')[1]/CanGeneral/CanLPduReceiveCalloutFunction/*"!](uint8 Hrh, Can_IdType CanId, uint8 CanDataLegth,
													const uint8* CanSduPtr);
[!ENDIF!]

[!NOCODE!][!//
[!IF "node:exists(as:modconf('Can')[1]/CanDemEventParameterRefs)"!] [!//
[!IF "not(node:exists(as:modconf('Can')[1]/CanDemEventParameterRefs/CAN_E_HARDWARE_ERROR))"!][!WARNING "DEM enabled but no DEM error configured"!][!ENDIF!]
[!ENDIF!][!//
[!ENDNOCODE!][!//

[!IF "node:exists(as:modconf('Can')[1]/CanDemEventParameterRefs/*)"!][!//
/* DEM Error Definitions */
#ifndef CAN_E_HARDWARE_ERROR
/** \brief Hardware failed */
#define CAN_E_HARDWARE_ERROR          ([!IF "not(node:empty(as:modconf('Can')[1]/CanDemEventParameterRefs/CAN_E_HARDWARE_ERROR))"!]DemConf_DemEventParameter_[!"node:name(node:ref(as:modconf('Can')[1]/CanDemEventParameterRefs/CAN_E_HARDWARE_ERROR))"!][!ELSE!][!ERROR "No Hardawre refernece is provided to the DEM error configured"!][!ENDIF!])
#endif
[!ENDIF!][!//

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */

/**
 * \brief Can Controller instance enum
 */
typedef enum
{
    /** \brief MCAN0 Controller Instance */
    CAN_CONTROLLER_INSTANCE_MCAN0 = 0x0U,
    /** \brief MCAN1 Controller Instance */
    CAN_CONTROLLER_INSTANCE_MCAN1 = 0x1U,
    /** \brief MCAN2 Controller Instance */
    CAN_CONTROLLER_INSTANCE_MCAN2 = 0x2U,
    /** \brief MCAN3 Controller Instance */
    CAN_CONTROLLER_INSTANCE_MCAN3 = 0x3U,
    /** \brief MCAN4 Controller Instance */
    CAN_CONTROLLER_INSTANCE_MCAN4 = 0x4U,
    /** \brief MCAN5 Controller Instance */
    CAN_CONTROLLER_INSTANCE_MCAN5 = 0x5U,
    /** \brief MCAN6 Controller Instance */
    CAN_CONTROLLER_INSTANCE_MCAN6 = 0x6U,
    /** \brief MCAN7 Controller Instance */
    CAN_CONTROLLER_INSTANCE_MCAN7 = 0x7U
    
} Can_ControllerInstance;

[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
/** \brief CAN Configuration struct declaration */
extern const struct Can_ConfigType_s [!"@name"!];
[!LOOP "CanController/*"!]
extern const struct Can_ControllerStruct_PC [!"../../@name"!]_PC_[!"@name"!];
[!ENDLOOP!]

/** \brief CAN Controller Pre Compile Configuration List */
extern const struct Can_ControllerStruct_PC
    *[!"@name"!]_CanController_List_PC[CAN_NUM_CONTROLLER];

/** \brief CAN Mailbox Pre Compile Configuration List */
extern const struct Can_MailboxStruct_PC
    *[!"@name"!]_CanHardwareObject_List_PC[CAN_NUM_MAILBOXES];

[!ENDLOOP!]
#ifdef __cplusplus
}
#endif

/**
* @}
*/

#endif /*CAN_CFG_H__*/

/**********************************************************************************************************************
 *  END OF FILE: Can_Cfg.h
 *********************************************************************************************************************/
