[!IF "as:modconf('Port')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile'"!]
/* ======================================================================
 *   Copyright (C) 2023 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/**
 *  \file     Port_Cfg.c
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for PORT MCAL driver
 *
 */

 /**********************************************************************************************************************
    Project: [!"$project"!]

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/

#define PORT_CFG_SOURCE

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "Std_Types.h"
#include "Port.h"
#include "hw_ctrl_core.h"
/**********************************************************************************************************************
 *  VERSION CHECK
 *********************************************************************************************************************/

/*  Version checking  */
#if ((PORT_SW_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U))||(PORT_SW_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
   #error "Version numbers of Port_Cfg.c and Port.h are inconsistent!"
#endif

#if ((PORT_CFG_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U))||(PORT_CFG_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of Port_Cfg.c and Port_Cfg.h are inconsistent!"
#endif

/**********************************************************************************************************************
 *  GLOBAL FUNCTION PROTOTYPES
 *********************************************************************************************************************/
[!IF "as:modconf('Port')[1]/PortGeneral/PortEnableIntrApi"!][!//
[!LOOP "as:modconf('Port')[1]/PortConfigSet/*"!][!//
[!LOOP "PortDioConfig/*"!][!//
[!VAR "NotificationVerify" = "PortDioInterruptNotification"!] [!VAR "Count" = "0"!] [!VAR "Idx" = "@index"!][!//
[!IF "not(node:empty(PortDioInterruptNotification)) and not(text:match(PortDioInterruptNotification,'NULL_PTR'))"!][!//
[!LOOP "../../PortDioConfig/*"!][!IF "@index < $Idx"!] [!IF "text:match(PortDioInterruptNotification,$NotificationVerify)"!] [!VAR "Count"="$Count+1"!] [!ENDIF!] [!ENDIF!] [!ENDLOOP!][!//
[!IF "$Count < '1'"!]
/** \brief Prototype for the callback function */
extern void [!"PortDioInterruptNotification"!](uint8 PortBankNum, uint8 PortBankChNum, Port_EdgeTrig Edge);
[!ENDIF!][!//
[!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDLOOP!][!//
[!ENDIF!][!//

/**********************************************************************************************************************
 *  LOCAL MACROS
 **********************************************************************************************************************/

/*MCAL: S MR:1.1 <APPROVED> "Reason - Start Section Code is also defined Port.h" */
#define PORT_START_SEC_CONFIG_DATA
/*MCAL: S MR:19.1 <APPROVED> "Reason - This is the format for specifying memory sections" */
#include "Port_MemMap.h"

[!LOOP "as:modconf('Port')[1]/PortConfigSet/*"!][!//
[!VAR "NumPortPins" = "0"!][!//
/*<PORT_PIN_CONFIGURATION>*/
static CONST( Port_PinConfigType, PORT_PBCFG) [!"@name"!]_PinConfig[] =
{
[!LOOP "PortContainer/*"!][!//
[!LOOP "PortPin/*"!][!//
[!WS "4"!]{
[!VAR "GPIOREG" = "'PORT_DIO_INVALID_REG_ID'"!][!//
[!VAR "GPIOREG_CH" = "'PORT_DIO_INVALID_CH_ID'"!][!//
[!VAR "GPIOREGID" = "0"!][!//
[!WS "9"!].Port_PinId = [!"PortPinId"!],
[!WS "9"!].Port_PullInhibitEnable = [!"PortPinInhibitEnable"!],
[!WS "9"!].Port_OutputOverride_Ctrl = [!"PortOutputOverrideCtrl"!],
[!WS "9"!].Port_InputOverride_Ctrl = [!"PortInputOverrideCtrl"!],
[!WS "9"!].Port_DirectionChangeable = [!"text:toupper(PortPinDirectionChangeable)"!],
[!WS "9"!].Port_PinModeChangeable = [!"text:toupper(PortPinModeChangeable)"!],
[!WS "9"!].Port_PinLevelValue = [!"PortPinLevelValue"!],
[!WS "9"!].Port_PinDirection = [!"PortPinDirection"!],
[!WS "9"!].Port_PinInitialMode =  PORT_PIN_MODE_[!"text:toupper(PortPinInitialMode)"!],
[!WS "9"!].Port_PullTypeSelect = [!"PortPullTypeSelect"!],
[!WS "9"!].Port_PinHSmasterEnable = [!"text:toupper(PortPinHSmasterEnable)"!],
[!WS "9"!].Port_PinHSmodeEnable = [!"text:toupper(PortPinHSmodeEnable)"!],
[!WS "9"!].Port_InversionSelect = [!"PortInputInversionSelect"!],
[!WS "9"!].Port_QualifierTypeSelect = [!"PortQualifierTypeSelect"!],
[!WS "9"!].Port_SlewControl = [!"PortSlewControlSelect"!],
[!WS "9"!].Port_GpioOwnerCore = [!"PortGpioOwnerCore"!],
[!WS "9"!].Port_NumPortModes = [!"num:i(count(PortPinMode/*))"!],
[!WS "9"!].Port_PinMode =
[!WS "9"!]{[!//
[!LOOP "PortPinMode/*"!][!//
[!VAR "gpiomatch" = "starts-with(node:value(.),'GPIO')"!][!//
[!VAR "portstr3" = "text:toupper(substring-before(node:value(.),'_'))"!][!//
[!IF "$gpiomatch"!][!//
[!ASSERT "$GPIOREG = 'PORT_DIO_INVALID_REG_ID'","Only one occurence of GPIO pin is supported for pin"!][!//
[!VAR "GPIOREG" = "num:i(substring-after($portstr3,'GPIO'))"!][!//
[!VAR "GPIOREG_CH" = "num:i(substring-after($portstr3,'GPIO'))"!][!//
[!IF "$GPIOREG_CH > '15'"!][!VAR "GPIOREG_CH" = "$GPIOREG_CH mod 32 "!][!ENDIF!][!//
[!ENDIF!][!//
[!WS "12"!][[!"@index"!]] =
[!WS "12"!]{
[!IF "starts-with(node:value(.),'PR0_UART0')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_PR0_UART0,
[!ELSEIF "starts-with(node:value(.),'PR0_MDIO')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_PR0_MDIO,
[!ELSEIF "starts-with(node:value(.),'PR0_IEP0')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_PR0_IEP0,
[!ELSEIF "starts-with(node:value(.),'PR0_ECAP0')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_PR0_ECAP0,
[!ELSEIF "starts-with(node:value(.),'PR0_PRU0')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_PR0_PRU0,
[!ELSEIF "starts-with(node:value(.),'PR0_PRU1')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_PR0_PRU1,
[!ELSEIF "starts-with(node:value(.),'EXT_REFCLK')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_EXT_REFCLK,
[!ELSEIF "starts-with(node:value(.),'SAFETY')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_SYSTEM,
[!ELSEIF "starts-with(node:value(.),'CLKOUT')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_CLKOUT,
[!ELSEIF "starts-with(node:value(.),'XBAROUT')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_XBAROUT,
[!ELSEIF "starts-with(node:value(.),'TRC')"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_TRC,
[!ELSEIF "starts-with(node:value(.),'GPIO')"!][!//
[!IF "$GPIOREG >= '0' and $GPIOREG < '32'"!][!//
[!VAR "GPIOREGID" = "1"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_GPIOAB,
[!ELSEIF "$GPIOREG >= '32' and $GPIOREG < '64'"!][!//
[!VAR "GPIOREGID" = "2"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_GPIOCD,
[!ELSEIF "$GPIOREG >= '64' and $GPIOREG < '96'"!][!//
[!VAR "GPIOREGID" = "3"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_GPIOEF,
[!ELSEIF "$GPIOREG >= '96' and $GPIOREG < '128'"!][!//
[!VAR "GPIOREGID" = "4"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_GPIOGH,
[!ELSEIF "$GPIOREG >= '128' and $GPIOREG < '160'"!][!//
[!VAR "GPIOREGID" = "5"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_GPIOI,
[!ELSE!][!ENDIF!][!//
[!ELSE!][!//
[!VAR "pinmode" = "text:toupper(substring-before(node:value(.),'_'))"!][!//
[!WS "16"!].mode = PORT_PIN_MODE_[!"$pinmode"!],
[!ENDIF!][!//
[!VAR "muxmode" = "num:i(substring-after(node:value(.),'MUXMODE_'))"!]
[!WS "16"!].muxmode = [!"$muxmode"!],
[!WS "12"!]},
[!ENDLOOP!][!//
[!IF "$GPIOREG = 'PORT_DIO_INVALID_REG_ID' and PortPinInitialGpioMuxmode != 'NULL'"!]
[!VAR "GPIOREG" = "num:i(substring-after(PortPinInitialGpioMuxmode,'GPIO'))"!][!//
[!VAR "GPIOREG_CH" = "num:i(substring-after(PortPinInitialGpioMuxmode,'GPIO'))"!][!//
[!IF "$GPIOREG_CH > '15'"!][!VAR "GPIOREG_CH" = "$GPIOREG_CH mod 32 "!][!ENDIF!][!//
[!IF "$GPIOREG >= '0' and $GPIOREG < '32'"!][!//
[!VAR "GPIOREGID" = "1"!][!//
[!ELSEIF "$GPIOREG >= '32' and $GPIOREG < '64'"!][!//
[!VAR "GPIOREGID" = "2"!][!//
[!ELSEIF "$GPIOREG >= '64' and $GPIOREG < '96'"!][!//
[!VAR "GPIOREGID" = "3"!][!//
[!ELSEIF "$GPIOREG >= '96' and $GPIOREG < '128'"!][!//
[!VAR "GPIOREGID" = "4"!][!//
[!ELSEIF "$GPIOREG >= '128' and $GPIOREG < '160'"!][!//
[!VAR "GPIOREGID" = "5"!][!//
[!ELSE!][!ENDIF!][!//
[!ENDIF!][!//
[!WS "9"!]},
[!WS "9"!].Port_PinDioRegId = [!IF "$GPIOREG != 'PORT_DIO_INVALID_REG_ID'"!]([!"num:i($GPIOREGID)"!] - 1U)[!ELSE!][!"$GPIOREG"!][!ENDIF!], /* GPIO register index is 0 based */
[!WS "9"!].Port_PinDioChannelId = [!IF "$GPIOREG != 'PORT_DIO_INVALID_REG_ID'"!][!"num:i($GPIOREG_CH)"!][!ELSE!][!"$GPIOREG"!][!ENDIF!],
[!WS "9"!].Port_RegOffsetAddr = [!"text:toupper(PortPinIdAddr)"!],
[!WS "9"!]/* Port_PinSignalName: [!"PortPinPeripheralSignal"!] */
[!WS "9"!]/* Port_PinName      : [!"PortPinName"!] */
[!WS "4"!]},
[!VAR "NumPortPins" = "$NumPortPins + 1"!][!//
[!ENDLOOP!][!//
[!ENDLOOP!][!//
};

[!VAR "NumGpioRegsSwitch" = "0"!][!//
[!LOOP "PortDioConfig/*"!][!//
[!VAR "NumGpioRegsSwitch" = "$NumGpioRegsSwitch + 1"!][!//
[!ENDLOOP!][!//
[!//
[!VAR "NumGpioRegs" = "0"!][!//
[!IF "$NumGpioRegsSwitch > '0'"!][!//
/*<PORT_PIN_CONFIGURATION>*/
static CONST( Port_DioRegConfigType, PORT_PBCFG) [!"@name"!]_DioConfig[] =
{
[!LOOP "PortDioConfig/*"!][!//
[!WS "4"!][[!"@index"!]] =
[!WS "4"!]{
[!VAR "crt_id" = "PortDioPinNumber"!][!//
[!VAR "n"="0"!][!//
[!LOOP "../../PortDioConfig/*"!][!//
[!VAR "crt_id1" = "PortDioPinNumber"!][!//
[!IF "$crt_id=$crt_id1"!][!VAR "n"="$n+1"!][!ENDIF!][!//
[!IF "$n > 1"!][!ERROR "[PortDioPinNumber] GPIO Pin Number is duplicated. GPIO Pin Number must be unique across configuration."!][!ENDIF!][!//
[!ENDLOOP!][!//
[!WS "9"!].Port_DioPinNumber = [!"PortDioPinNumber"!],
[!WS "9"!].Port_PinSelectEdgeTrigger = [!"PortPinSelectEdgeTrigger"!],
[!WS "9"!].Port_PinSelectInterruptType = [!"PortPinSelectInterruptType"!],
#if(PORT_ENABLE_INTR_API == STD_ON)
[!VAR "PINNUM" = "PortDioPinNumber"!][!//
[!VAR "GPIOBNKNUM1" = "0"!][!//
[!IF "$PINNUM >= '0' and $PINNUM <= '15'"!][!VAR "GPIOBNKNUM1" = "0"!][!ELSEIF "$PINNUM >= '16' and $PINNUM <= '31'"!][!VAR "GPIOBNKNUM1" = "1"!][!ELSEIF "$PINNUM >= '32' and $PINNUM <= '47'"!][!VAR "GPIOBNKNUM1" = "2"!][!ELSEIF "$PINNUM >= '48' and $PINNUM <= '63'"!][!VAR "GPIOBNKNUM1" = "3"!][!ELSEIF "$PINNUM >= '64' and $PINNUM <= '79'"!][!VAR "GPIOBNKNUM1" = "4"!][!ELSE!][!ENDIF!][!//
[!IF "$PINNUM >= '80' and $PINNUM <= '95'"!][!VAR "GPIOBNKNUM1" = "5"!][!ELSEIF "$PINNUM >= '96' and $PINNUM <= '111'"!][!VAR "GPIOBNKNUM1" = "6"!][!ELSEIF "$PINNUM >= '112' and $PINNUM <= '127'"!][!VAR "GPIOBNKNUM1" = "7"!][!ELSEIF "$PINNUM >= '128' and $PINNUM <= '138'"!][!VAR "GPIOBNKNUM1" = "8"!][!ELSE!][!ENDIF!][!//
[!VAR "NotificationVerify" = "PortDioInterruptNotification"!][!//
[!IF "text:match(PortPinSelectInterruptType,'PORT_BANK_INTR')"!][!//
[!LOOP "../../PortDioConfig/*"!][!//
[!IF "text:match(PortPinSelectInterruptType,'PORT_BANK_INTR')"!][!//
[!VAR "PINNUM" = "PortDioPinNumber"!][!//
[!VAR "GPIOBNKNUM2" = "0"!][!//
[!IF "$PINNUM >= '0' and $PINNUM <= '15'"!][!VAR "GPIOBNKNUM2" = "0"!][!ELSEIF "$PINNUM >= '16' and $PINNUM <= '31'"!][!VAR "GPIOBNKNUM2" = "1"!][!ELSEIF "$PINNUM >= '32' and $PINNUM <= '47'"!][!VAR "GPIOBNKNUM2" = "2"!][!ELSEIF "$PINNUM >= '48' and $PINNUM <= '63'"!][!VAR "GPIOBNKNUM2" = "3"!][!ELSEIF "$PINNUM >= '64' and $PINNUM <= '79'"!][!VAR "GPIOBNKNUM2" = "4"!][!ELSE!][!ENDIF!][!//
[!IF "$PINNUM >= '80' and $PINNUM <= '95'"!][!VAR "GPIOBNKNUM2" = "5"!][!ELSEIF "$PINNUM >= '96' and $PINNUM <= '111'"!][!VAR "GPIOBNKNUM2" = "6"!][!ELSEIF "$PINNUM >= '112' and $PINNUM <= '127'"!][!VAR "GPIOBNKNUM2" = "7"!][!ELSEIF "$PINNUM >= '128' and $PINNUM <= '138'"!][!VAR "GPIOBNKNUM2" = "8"!][!ELSE!][!ENDIF!][!//
[!IF "(not(text:match(PortDioInterruptNotification,$NotificationVerify))) and $GPIOBNKNUM1 = $GPIOBNKNUM2"!] [!ERROR "[PortDioInterruptNotification] Port Bank Interrupts should have unique port interrupt notification per BANK"!] [!ENDIF!][!//
[!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDIF!][!//
[!WS "9"!].Port_DioInterruptNotification = (Port_IsrNotificationType) [!"PortDioInterruptNotification"!],
#endif
[!WS "4"!]},
[!VAR "NumGpioRegs" = "$NumGpioRegs + 1"!][!//
[!ENDLOOP!][!//
};
[!ENDIF!][!//

/*</PORT_PIN_CONFIGURATION>*/
CONST(Port_ConfigType, PORT_PBCFG) Port_Config =
{
    .NumberOfPortPins = [!"num:i($NumPortPins)"!],
    .PinConfig_pt = [!"@name"!]_PinConfig,
    .NumberOfGPIORegs = [!"num:i($NumGpioRegs)"!],
[!IF "$NumGpioRegsSwitch > '0'"!][!//
    .DioConfig_pt = [!"@name"!]_DioConfig,
[!ELSE!][!//
	.DioConfig_pt = (Port_DioRegConfigType *) NULL_PTR,
[!ENDIF!][!//
};

[!ENDLOOP!][!//
#define PORT_STOP_SEC_CONFIG_DATA
#include "Port_MemMap.h"

/**********************************************************************************************************************
 *  END OF FILE: Port_Cfg.c                                                                                         *
 **********************************************************************************************************************/
[!ELSE!]
/* The last generated configuration variant is not Pre-Compile variant. Refer Port_PBcfg.c. */
[!ENDIF!]


